name             'box_basic'
maintainer       'github@jamesjj.net'
maintainer_email 'github@jamesjj.net'
license          'All rights reserved'
description      'Installs/Configures instances'
long_description      'Installs/Configures instances'
version          '0.1.0'

depends 'users'
depends 'chef-solo-search'
depends 'yum-epel'
