name             'box_basic'
maintainer       'github@jamesjj.net'
maintainer_email 'github@jamesjj.net'
license          'MIT'
description      'Installs/Configures instances'
long_description      'Installs/Configures instances'
version          '0.1.3'

depends 'users'
depends 'chef-solo-search'
depends 'yum-epel'
depends 'shell_preferences'
